//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NodeApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add new card.
        /// </summary>
        public static string AddNewCard {
            get {
                return ResourceManager.GetString("AddNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create new node.
        /// </summary>
        public static string AddNewNodeTooltip {
            get {
                return ResourceManager.GetString("AddNewNodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu pack://application:,,,/Images/ContextMenuIcons/arrowDown.png.
        /// </summary>
        public static string ArrowDown {
            get {
                return ResourceManager.GetString("ArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu pack://application:,,,/Images/ContextMenuIcons/arrowLeft.png.
        /// </summary>
        public static string ArrowLeft {
            get {
                return ResourceManager.GetString("ArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu pack://application:,,,/Images/ContextMenuIcons/arrowRight.png.
        /// </summary>
        public static string ArrowRight {
            get {
                return ResourceManager.GetString("ArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu pack://application:,,,/Images/ContextMenuIcons/arrowUp.png.
        /// </summary>
        public static string ArrowUp {
            get {
                return ResourceManager.GetString("ArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Available Labels.
        /// </summary>
        public static string AvailableLabels {
            get {
                return ResourceManager.GetString("AvailableLabels", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click on any label to delete it.
        /// </summary>
        public static string AvailableLabelsTooltip {
            get {
                return ResourceManager.GetString("AvailableLabelsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Background Color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu by WWS.
        /// </summary>
        public static string byWWS {
            get {
                return ResourceManager.GetString("byWWS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Card Content.
        /// </summary>
        public static string CardContent {
            get {
                return ResourceManager.GetString("CardContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Left click to edit content | Right click to navigate\delete.
        /// </summary>
        public static string CardTooltip {
            get {
                return ResourceManager.GetString("CardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create New Label.
        /// </summary>
        public static string CreateNewLabel {
            get {
                return ResourceManager.GetString("CreateNewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete This Card.
        /// </summary>
        public static string DeleteCard {
            get {
                return ResourceManager.GetString("DeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click to delete.
        /// </summary>
        public static string DeleteLabelsTooltip {
            get {
                return ResourceManager.GetString("DeleteLabelsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete This Node.
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string EditNode {
            get {
                return ResourceManager.GetString("EditNode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter Room.
        /// </summary>
        public static string EnterRoom {
            get {
                return ResourceManager.GetString("EnterRoom", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter room name to proceed!.
        /// </summary>
        public static string EnterRoomName {
            get {
                return ResourceManager.GetString("EnterRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Foreground Color.
        /// </summary>
        public static string ForegroundColor {
            get {
                return ResourceManager.GetString("ForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Help me!.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Can&apos;t be already used title.
        /// </summary>
        public static string InvalidLabelNameTooltip {
            get {
                return ResourceManager.GetString("InvalidLabelNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create new label based on the parameters above (title can&apos;t be duplicated).
        /// </summary>
        public static string InvalidLabelNameTooltip2 {
            get {
                return ResourceManager.GetString("InvalidLabelNameTooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Labels.
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move Card Down.
        /// </summary>
        public static string MoveCardDown {
            get {
                return ResourceManager.GetString("MoveCardDown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move Card Left.
        /// </summary>
        public static string MoveCardLeft {
            get {
                return ResourceManager.GetString("MoveCardLeft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move Card Right.
        /// </summary>
        public static string MoveCardRight {
            get {
                return ResourceManager.GetString("MoveCardRight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move Card Up.
        /// </summary>
        public static string MoveCardUp {
            get {
                return ResourceManager.GetString("MoveCardUp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move Node Left.
        /// </summary>
        public static string MoveNodeLeft {
            get {
                return ResourceManager.GetString("MoveNodeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move Node Right.
        /// </summary>
        public static string MoveNodeRight {
            get {
                return ResourceManager.GetString("MoveNodeRight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Card.
        /// </summary>
        public static string NewCard {
            get {
                return ResourceManager.GetString("NewCard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Node.
        /// </summary>
        public static string NewNode {
            get {
                return ResourceManager.GetString("NewNode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click twice to edit.
        /// </summary>
        public static string NodeTitleTooltip {
            get {
                return ResourceManager.GetString("NodeTitleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Properties.
        /// </summary>
        public static string PropertiesTooltip {
            get {
                return ResourceManager.GetString("PropertiesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu pack://application:,,,/Images/ContextMenuIcons/redCross.png.
        /// </summary>
        public static string RedCross {
            get {
                return ResourceManager.GetString("RedCross", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Room Name.
        /// </summary>
        public static string RoomName {
            get {
                return ResourceManager.GetString("RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
    }
}
